spring.application.name=reservex

spring.datasource.url=jdbc:postgresql://localhost:5432/reservex
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=reservex-super-secret-jwt-key-for-development-2026-authentication-service-key
jwt.access-token-expiry-ms=3600000
jwt.refresh-token-expiry-ms=2592000000

logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR
logging.level.org.springframework.security=WARN
logging.level.org.springdoc=WARN